### ISSUE TITLE
GPGGA: NMEA sentence is too long!

### ISSUE THREAD

**Issue by dvtomas** [nsforth/nmea0183#12]
I get the error e.g. for the following real world (I don't remember the actual GPS receiver) message: `$GPGGA,172814.0,3723.46587704,N,12202.26957864,W,2,6,1.2,18.893,M,-25.669,M,2.0,0031*4F\r\n`

**Comment by nsforth** [comment]
Your receiver violates NMEA0183 spec that clearly states max message len. Between $ and CRLF characters should be no more than 79 chars. 
![NMEA0183 spec](https://github.com/user-attachments/assets/573a81a5-42ac-4212-b527-991aa8c7cfb3)
I have and idea to fix it with "strict" crate feature which should be "true" by default.
strict=false will change max sentence size to something suitable, for example 120 chars.

**Comment by dvtomas** [comment]
Thank you for looking into this. That would solve this to me. I think raising the limit to 100 chars would be enough. I'm not sure about the feature naming, though. As this controls the length only (as of yet), a `strict_length` might be more appropriate?

Also, I'm not sure which should be the default. My guess is that very few devices are so memory constrained that extra 20 bytes would matter at all, but the potential for an unexpected error with a non-compliant GPS receiver can be frustrating. But it's your choice of course, I'll be happy with any solution.
