### ISSUE TITLE
GPGGA without altitude not parsed

### ISSUE THREAD

**Issue by dvtomas** [nsforth/nmea0183#13]
I've the following real world message: 

`$GPGGA,160545,5008.6263,N,01422.4224,E,1,03,3.6,,M,45.0,M,,*61` . The altitude is missing, but other data is OK. This message is NOT parsed.

It may make sense to make the `GGA.altitude` field an `Option`?

**Comment by nsforth** [comment]
Hi. I checked nmea specs. Nothing about altitude nullability, but there is a general rule which says "fields may be null if there is no valid data".
Usually receivers won't send GGA if they have no data at all, but in your case it looks like 2dfix with fixed lat/lon only.
So it seems ok to make it optional.
