### ISSUE TITLE
Can't determine number of sattelites until a position is found

### ISSUE THREAD

**Issue by timbod7** [nsforth/nmea0183#3]
Thanks for this library - it's saved me effort in getting a small embedded GPS device up and running.

One issue is that the number of satellites being received is part of the GGA message, but the parser only returns GGA results once a fix is available.

A solution would be to have the parser output 2 types of GGA messages, with and without a fix. ie change to something like:

```
pub enum ParseResult {
    RMC(Option<RMC>),
    GGA(GGA),
    GGANoFix(GGANoFix),
    GLL(Option<GLL>),
    VTG(Option<VTG>),
}

pub struct GGANoFix {
    pub sat_in_use: u8,
}
```
Is this a reasonably solution? Would you accept a PR for this?

**Comment by timbod7** [comment]
Actually, just realized that parsing of the GSA messages is probably a better solution for this.

**Comment by nsforth** [comment]
Hi!

Yes, GSA it a truly better way! I have plans to implement GSA and GSV but for me it's not a high priority feature because no one asks that feature yet. :)
If you need GSA support you may open a feature request.
