### ISSUE TITLE
 Incorrect Condition for Minutes Range Check in parse_from_hhmmss Function

### ISSUE THREAD

**Issue by p3zhy** [nsforth/nmea0183#5]
The` parse_from_hhmmss` function in the NMEA parser library contains a conditional check that limits the range of minutes to be less than 59. This condition is incorrect as it should be m < 60 to include minutes ranging from 0 to 59.

**Comment by nsforth** [comment]
Thanks for contribution! Merged. I'll bump new version in a few hours.
